-- CreateTable
CREATE TABLE "Settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "emailNotificationsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emailNewAppointments" BOOLEAN NOT NULL DEFAULT true,
    "emailNewUsers" BOOLEAN NOT NULL DEFAULT true,
    "emailIncompleteAppointments" BOOLEAN NOT NULL DEFAULT true,
    "emailDailySummary" BOOLEAN NOT NULL DEFAULT false,
    "notificationEmail" TEXT NOT NULL DEFAULT 'irena@beautylab.hr',
    "workingDays" TEXT NOT NULL DEFAULT '["monday","tuesday","wednesday","thursday","friday"]',
    "workingHoursStart" TEXT NOT NULL DEFAULT '09:00',
    "workingHoursEnd" TEXT NOT NULL DEFAULT '18:00',
    "breakStart" TEXT,
    "breakEnd" TEXT,
    "holidays" TEXT,
    "defaultPointsPerService" INTEGER NOT NULL DEFAULT 10,
    "bronzeThreshold" INTEGER NOT NULL DEFAULT 0,
    "silverThreshold" INTEGER NOT NULL DEFAULT 100,
    "goldThreshold" INTEGER NOT NULL DEFAULT 300,
    "platinumThreshold" INTEGER NOT NULL DEFAULT 500,
    "inviteCodeBonusPoints" INTEGER NOT NULL DEFAULT 15,
    "autoUpdateTiers" BOOLEAN NOT NULL DEFAULT true,
    "notificationRefreshInterval" INTEGER NOT NULL DEFAULT 30,
    "showNewAppointmentNotifications" BOOLEAN NOT NULL DEFAULT true,
    "showTodayAppointmentNotifications" BOOLEAN NOT NULL DEFAULT true,
    "showNewUserNotifications" BOOLEAN NOT NULL DEFAULT true,
    "showIncompleteNotifications" BOOLEAN NOT NULL DEFAULT true,
    "notificationSoundEnabled" BOOLEAN NOT NULL DEFAULT false,
    "autoCompleteAppointments" BOOLEAN NOT NULL DEFAULT false,
    "autoCompleteAfterHours" INTEGER,
    "autoDeleteOldAppointments" BOOLEAN NOT NULL DEFAULT false,
    "autoDeleteAfterDays" INTEGER,
    "autoSendReminderEmails" BOOLEAN NOT NULL DEFAULT false,
    "reminderEmailHoursBefore" INTEGER,
    "theme" TEXT NOT NULL DEFAULT 'light',
    "language" TEXT NOT NULL DEFAULT 'hr',
    "dateFormat" TEXT NOT NULL DEFAULT 'DD.MM.YYYY',
    "timeFormat" TEXT NOT NULL DEFAULT '24h',
    "timezone" TEXT NOT NULL DEFAULT 'Europe/Zagreb',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
